export const additionalProducts=[
 {name:'Canoa Chanel Grande',price:'620,00',size:'26 × 36 × 12 cm',description:'Um bolso frontal e um bolso traseiro com zíper, alça de ombro e alça transversal, uma divisória com dois bolsos internos, sendo um com zíper e outro sem zíper.',image:'/catalog-original/canoa-chanel-grande.png',category:'Grandes'},
 {name:'Bolsa Blue',price:'620,00',size:'26 × 37 × 17 cm',description:'Bolsa de textura mole, com duas alças: uma de ombro e uma longa. Dois bolsos frontais com Fexo de ímã, um bolso traseiro com zíper, uma divisória com zíper e dois bolsos internos.',image:'/catalog-original/bolsa-blue.png',category:'Grandes'},
 {name:'Bolsa Tânia',price:'620,00',size:'27 × 34 × 17 cm',description:'Bolsa estruturada, com duas alças de mão reguláveis e uma alça longa. Um bolso frontal com zíper, dois bolsos laterais com zíper, uma divisória e dois bolsos internos.',image:'/catalog-original/bolsa-tania.png',category:'Estruturadas'},
 {name:'Bolsa Nadine',price:'420,00',size:'15 × 22 × 8 cm',description:'Com tampa e Fexo, uma divisória e dois bolsos internos, um bolso na parte de trás, uma alça de mão e uma alça transversal.',image:'/catalog-original/bolsa-nadine.png',category:'Pequenas'},
 {name:'Bolsa Bia',price:'420,00',size:'16 × 22 × 7 cm',description:'Alça de corrente com tampa e Fexo, uma divisória e um bolso com zíper.',image:'/catalog-original/bolsa-bia.png',category:'Pequenas'},
 {name:'Bolsa Chanel PP',price:'390,00',size:'15 × 19 × 8 cm',description:'Com tampa e Fexo, uma divisória com bolso interno e alça na corrente trançada com couro.',image:'/catalog-original/bolsa-chanel-pp.png',category:'Pequenas'},
 {name:'Bolsa Liliam',price:'629,00',size:'23 × 32 × 8 cm',description:'Alça regulável na corrente e no couro, duas divisórias com três bolsos internos, sendo um com zíper.',image:'/catalog-original/bolsa-liliam.png',category:'Pequenas'},
 {name:'Bolsa Liana',price:'620,00',size:'27 × 25 × 14 cm',description:'Duas divisórias, três bolsos internos, duas alças de ombro e uma alça transversal.',image:'/catalog-original/bolsa-liana.png',category:'Estruturadas'},
 {name:'Bolsa Carteiro',price:'620,00',size:'25 × 30 × 18 cm',description:'Alça longa transversal, cinco bolsos com zíper, dois bolsos grandes e dois bolsos laterais.',image:'/catalog-original/bolsa-carteiro.png',category:'Grandes'},
 {name:'Bolsa Saco Corrente',price:'620,00',size:'32 × 32 × 13 cm',description:'Uma divisória com dois bolsos, dois bolsos externos nas laterais e alça de corrente com couro entrelaçado.',image:'/catalog-original/bolsa-saco-corrente.png',category:'Grandes'}
];
